### ISSUE TITLE
Add Outlook 2016 Support

### ISSUE THREAD

**Issue by geoffreak** [ua-parser/uap-core#132]
I came here from [the node library that uses this list](https://github.com/3rd-Eden/useragent) when I noticed Outlook 2016 was missing.

[User agent strings:](https://udger.com/resources/ua-list/browser-detail?browser=Outlook%202016)
```
Microsoft Office/16.0 (Microsoft Outlook Mail 16.0.6416; Pro)

Microsoft Office/16.0 (Windows NT 10.0; Microsoft Outlook 16.0.6326; Pro)

Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 10.0; WOW64; Trident/8.0; .NET4.0C; .NET4.0E; .NET CLR 2.0.50727; .NET CLR 3.0.30729; .NET CLR 3.5.30729; Microsoft Outlook 16.0.6366; ms-office; MSOffice 16)
```

I think the settings will be close to:
```yaml
  # Outlook 2016
  - regex: 'Microsoft Outlook 16\.\d+\.\d+'
    family_replacement: 'Outlook'
    v1_replacement: '2016'
```
