### ISSUE TITLE
Return Apple Watch model info in line with rest of Apple devices

### ISSUE THREAD

**Issue by wallin** [ua-parser/uap-core#435]
The model information for an Apple Watch is currently returned as follows:

```yaml
  - user_agent_string: 'atc/1.0 watchOS/5.1.3 model/Watch3,4 hwp/t8004 build/16S535 (6; dt:156)'
    family: 'Apple Watch'
    brand: 'Apple'
    model: 'Apple Watch 3,4'
```

However for other Apple devices the raw model information is kept, eg.

```yaml
  - user_agent_string: 'Mozilla/5.0 (iPhone6,1; iPhone; U; CPU OS 7_0_4 like Mac OS X; ar_SA) com.google.GooglePlus/29676 (KHTML, like Gecko) Mobile/N51AP (gzip)'
    family: 'iPhone'
    brand: 'Apple'
    model: 'iPhone6,1'
```

Apple Watch model should be returned as eg. `Watch3,4` for consistency. The word "Apple" belongs only in the brand information

If you agree with this, I'd be happy to do a PR
