### ISSUE TITLE
Add detection for Edge Chromium

### ISSUE THREAD

**Issue by devsmaster07** [ua-parser/uap-core#443]
Edge Chromium is currently showing up as Chrome. Would it be possible to add detection for it?

**Comment by heowc** [comment]
Me too.

The following is the user agent when installing chronium based edge.
- Edge Version: 79.0.309.60 (Official Build) beta (64Bits)
- UserAgent Header
    > Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.117 Safari/537.36 Edg/79.0.309.60

**Comment by heowc** [comment]
Related
- https://docs.microsoft.com/en-us/microsoft-edge/web-platform/user-agent-string
- https://blogs.windows.com/msedgedev/2017/10/05/microsoft-edge-ios-android-developer/

**Comment by heowc** [comment]
@devsmaster07 ,

I noticed that  [the yaml file](https://github.com/ua-parser/uap-core/blob/master/regexes.yaml)  versions in master branch and `uap-java:1.4.3` are different. As a master branch standard, it is supported for Edge for Desktop. However, it is not compatible with iOS and Android.

I solved this by adding: Of course, this may not be the right answer, or it may be inefficient.

```yaml
# Android
- regex: '(Chrome)/(\d+)\.(\d+)\.(\d+)\.(\d+) Mobile(?:[ /]|$).*[ +]EdgA'
  family_replacement: 'Mobile Edge'
# iOS
- regex: '(iPod|iPod touch|iPhone|iPad);.*CPU.*OS[ +](\d+)_(\d+)(?:_(\d+)|).*Mobile.*[ +]EdgiOS'
  family_replacement: 'Mobile Edge'
```

Add the above and run test to see that there is no problem.
